print("This program calculates and displays travel expenses")
budget = float(input("Enter Budget:"))
location = input("Enter your travel destination :")
fuel = float(input("How much do you think you will spend on gas ? "))
hotel = float(input("Approximately, how much will you need for Accomodation/hotel?"))
food = float(input("Last, how much do you need for food?"))
balance = budget - (fuel+hotel+food)
print("---------------Travel Expenses---------------")
print("Location:\t\t",location)
print("Initial Budget:\t\t$",budget)
print("Fuel:\t\t\t$",fuel)
print("Accomodation:\t\t$",hotel)
print("Food:\t\t\t$",food)
print("---------------------------------------------")
print("Remaining Balance :\t$",balance)
